//! Vocabulary packs: curated domain term lists (canonical spelling -> known
//! mis-hearings) that the ASR-mishearing corrector consults as a
//! LOWEST-priority fuzzy tier, after the user dictionary and builtin seeds.
//!
//! Packs are OFF by default; each is toggled independently in Settings
//! (`Settings::enabled_packs`). Data ported from the reference
//! implementation's `Resources/Packs/*.json` (tech, medical, legal, brands,
//! names) — canonical spellings and alias lists are kept verbatim.

/// One vocabulary pack.
pub struct VocabPack {
    /// Stable id: "tech" | "medical" | "legal" | "brands" | "names".
    pub id: &'static str,
    /// Display name.
    pub name: &'static str,
    /// One-line description for the UI.
    pub description: &'static str,
    /// canonical -> known mis-hearings.
    pub terms: &'static [(&'static str, &'static [&'static str])],
}

/// Number of canonical terms in a pack (for the UI's term count).
impl VocabPack {
    pub fn term_count(&self) -> usize {
        self.terms.len()
    }
}

pub const PACKS: &[VocabPack] = &[
    VocabPack { id: "tech", name: "Technology", description: "Programming, software engineering and DevOps terms.", terms: &[
        ("accept", &["ekipt", "oxcept"]),
        ("AngularJS", &["angularge", "ingiolarge", "ingiolarts", "inkyolarge"]),
        ("async", &["esync", "isinc", "isync", "osinc", "ozync"]),
        ("autoscaling", &["autosculum", "autoskalong", "etroskilling"]),
        ("backpressure", &["backbrushery", "backbushery", "buckbrusher"]),
        ("backpropagation", &["backpapagine", "backpropagatine"]),
        ("Bazel", &["bazool", "beazel", "buesil"]),
        ("Blazor", &["blizzr", "blueser"]),
        ("bluegreen", &["bleagreen", "bluegroon"]),
        ("cache", &["catca"]),
        ("cherrypick", &["cherapak", "cheropick", "cheropok", "cherubick", "chorepik", "choropic", "chorpit", "churapik"]),
        ("CLI", &["clarf"]),
        ("codec", &["cadoak", "codic", "kodich", "kodok", "sedec"]),
        ("computervision", &["simputervision"]),
        ("Consul", &["consal", "sinsil"]),
        ("Couchbase", &["corchbase"]),
        ("csharp", &["seashaw"]),
        ("Cypress", &["cypras", "cypresh"]),
        ("deadletter", &["detteldeer", "dettelder"]),
        ("Dockerfile", &["decaphile", "dickerfile", "dochfil", "dockerfilla", "docphilo"]),
        ("DocumentDB", &["dacumentdb", "decumantdb", "ducumentdb"]),
        ("dotnet", &["datnet", "dotnath"]),
        ("ECDSA", &["actsa"]),
        ("finetuning", &["fanatuning", "fanetuning", "finetunong", "finetunung", "fintenang", "fituning"]),
        ("GenAI", &["genow"]),
        ("Gerrit", &["gurret", "gurrit", "jarat", "jarub", "jeriff", "jerrith"]),
        ("HSTS", &["hsdesh", "hsdsh"]),
        ("ImageMagick", &["amagemagic", "imagemagac"]),
        ("InVision", &["anvision", "infison"]),
        ("Kerberos", &["corberos", "kaberos", "kberos", "kberus", "kerberas"]),
        ("lakehouse", &["likaosu"]),
        ("lexer", &["lexir", "loxer"]),
        ("linkedlist", &["lenkidlist", "lunkedlist"]),
        ("localStorage", &["licklestorage", "locustoragi"]),
        ("LSTM", &["lsdmh"]),
        ("metaprogramming", &["metaprogrammong"]),
        ("nanoid", &["nanoad", "nanoaud", "nanoe", "nanoide", "nanood", "nanoord", "nanorad", "nomoid", "nonoid", "nunlate"]),
        ("nginx", &["mbunks", "nganks", "ngunks", "njenx", "unjinx"]),
        ("nonblocking", &["nonbuking", "nunbooking"]),
        ("nonce", &["nints", "nonco", "nonkar", "nuncar", "nunts"]),
        ("NuGet", &["nagit", "negit", "neuda", "newgap", "newgat", "nujet"]),
        ("OpenAI", &["apernye", "eperknife", "epini", "openo", "openr"]),
        ("OpenCV", &["epink", "opanc", "openc", "opinc", "opunk"]),
        ("OpenVPN", &["appendman", "ipinpen", "occamfon", "opemphman", "openfun", "openpen", "openpon", "ophonfm", "oppenfmann"]),
        ("OTel", &["othil", "ottil"]),
        ("pacman", &["pacmin", "pecman"]),
        ("pentest", &["pantice", "pantist", "pentist", "pentust"]),
        ("PHPUnit", &["pghbunith"]),
        ("Postgres", &["pestvers", "piscus", "postgrish"]),
        ("RabbitMQ", &["rabbitk", "rabek", "rabok"]),
        ("ReactJS", &["roxchs", "ryaksch"]),
        ("reCAPTCHA", &["racaptcha", "rackapcha", "recapcha", "recapta", "rockcha", "rockupture"]),
        ("RedHat", &["ridat", "rodhat", "rudhat"]),
        ("referer", &["rafera", "referra", "referrar", "referrier"]),
        ("regex", &["ragex", "regix", "regox", "regux", "rigox", "rogerx", "rogiks", "rugex"]),
        ("regexp", &["regext", "regoxp", "rejexp", "rugexp", "rygex", "rygixp"]),
        ("Rider", &["ridier"]),
        ("route", &["rauto", "ryute"]),
        ("RSpec", &["aspuk", "rspoc"]),
        ("SciPy", &["scapey", "scuppy"]),
        ("SFTP", &["sfdph"]),
        ("spaCy", &["spasi", "spoci", "sposy", "spusy"]),
        ("Spinnaker", &["spanaca", "spanaker", "spinacker", "spinaker", "spinnacker", "spinnager"]),
        ("stresstest", &["strawst", "stristies", "stristist", "strostist", "strustist"]),
        ("Tauri", &["tiyuri"]),
        ("tcpdump", &["tcpdimp"]),
        ("Tekton", &["tactan", "tacton", "tectan", "tectin", "tiktin", "tocton"]),
        ("timezone", &["tanzono", "temizone", "tumazone"]),
        ("trie", &["triwo", "tryou"]),
        ("Veracode", &["ferricode", "vericode", "vericodi", "vertode", "vurecode"]),
        ("VLAN", &["velun"]),
        ("VueJS", &["viewges", "viewodge"]),
        ("warmup", &["warmap", "warmapp", "wormup"]),
        ("WebM", &["wabam", "wabum", "webem", "webum", "wobben", "wubam"]),
        ("winget", &["wengit", "wenjet", "winggut", "wingot", "wingut", "winkit"]),
        ("Zeplin", &["sipplin", "suprin", "zipplin", "zuplin"]),
    ] },
    VocabPack { id: "medical", name: "Medical", description: "Medicine, anatomy, symptoms and treatments.", terms: &[
        ("acetaminophen", &["acidaminophan", "acidaminophen", "ostaminofin"]),
        ("acne", &["achni"]),
        ("amoxicillin", &["amaxicylin", "amaxisillin", "amaxysilin", "amexicillin", "amexysilin", "anaxicillin", "armaticillin", "emoxicillin", "eumoxacillin", "imokasillin", "omuxicilian"]),
        ("ankle", &["anclay", "anclo"]),
        ("appendectomy", &["apendectomy", "appendicdomy", "appendicme", "appendicomy", "opendectomy", "upendectomy"]),
        ("ascites", &["acidos", "esites", "essites"]),
        ("bisacodyl", &["bisacodil", "bisaystill", "bosaccodil", "bosacodil", "pisacodil"]),
        ("brainstem", &["bryinston"]),
        ("bruit", &["bewatt", "brayot", "breut"]),
        ("cardioversion", &["cardiovacin", "cardiovasian", "cardiovercyan", "carduovicine"]),
        ("cecum", &["kakum", "secan", "sesum"]),
        ("Celexa", &["colxa", "kolexa", "selexa", "selixo", "sellax"]),
        ("cervix", &["corvix", "curvix", "servax", "servix", "servox", "surfax"]),
        ("cholecystectomy", &["cholsystectomy", "coalcystectomy", "colcystectomy", "colsystectomy"]),
        ("clonazepam", &["clonasbum", "clonaspum"]),
        ("codeine", &["codini", "codonu"]),
        ("colchicine", &["calciosene", "celchessine", "colchicino", "culchicene", "culturesyn", "seltchicine", "silchacine", "silchicine"]),
        ("cyclobenzaprine", &["cyclobensprini", "cyclobenzoprene", "cyclobenzprene", "cyclobenzprina", "cyclobenzprini", "cyclubenzoprene"]),
        ("diphenhydramine", &["daphenhydramine", "diffinhydramine", "diffinhydramini"]),
        ("distension", &["darstin"]),
        ("dysuria", &["dysaria", "dysary", "dyseraia", "dyseri", "dyseria", "dyserio", "dysoria"]),
        ("echocardiogram", &["echardiogram", "echicardiogram", "icacardiogram", "otchacardiogram"]),
        ("erythema", &["arithama", "arithema", "erifema", "erithama", "erithema", "erithima", "orithema", "orthema"]),
        ("fexofenadine", &["fexofmatine", "fexofnadine", "fexofnadino", "foxofnadine", "fuxofhmadine", "vexofnadin"]),
        ("Fosamax", &["fasamax", "fasimax", "fossamax", "fossamix", "fossamux"]),
        ("gallop", &["gillip", "golop", "gullop", "gullup"]),
        ("gallstones", &["gallstonas", "galsonish", "galstonish", "galstonus", "gaulstonish", "gausterness", "gulstonos"]),
        ("gemfibrozil", &["gamphabrazil", "gemfabrazal", "gemfibrazel", "gemphabrosal", "gemphibrazol"]),
        ("gland", &["glend", "glind", "glond", "glund"]),
        ("goiter", &["goidir", "goita", "goite", "gorta"]),
        ("hematemesis", &["hamaknis", "hematenessis"]),
        ("hemoptysis", &["haemopsys", "hematizers", "hemopdys", "hemophtesis", "hemoptasis", "hemoptasys", "hemupdissus", "hermoptosis", "homopasis", "symoptosis"]),
        ("humerus", &["hamarus", "heimrus", "hemorrhus", "homeress", "homeris", "humorush"]),
        ("Humira", &["hamira", "hermera", "hermira", "himira", "humai", "humeira", "humeya", "humiro"]),
        ("hydralazine", &["hydrolasine", "hydrolasing", "hydrolazeno", "hydrolazini", "hyrolazine"]),
        ("ileum", &["earleem", "earlium", "elium", "ulilam"]),
        ("incidence", &["ansidence", "incidenc", "incidenci", "incidencife", "incidenka", "insidence", "oncidents"]),
        ("Januvia", &["genuvia", "genuvii", "genuvio", "ginuvia", "januvi", "januview"]),
        ("Keppra", &["kepra"]),
        ("Klonopin", &["clanopin", "clanpin", "clenopin", "clonopen", "clunapin", "klanapin", "klonopen"]),
        ("Lantus", &["lantush", "lintus", "luntis"]),
        ("leukopenia", &["laucopenia", "leucopy", "leukopnei", "locopenia", "lukopemayu", "lukopi"]),
        ("levodopa", &["levadopa", "levadope", "levadopo", "lividopa"]),
        ("lipase", &["lapasi", "lapasu", "lipace", "lipsay", "loopace", "lopasi", "lupaces"]),
        ("Lipitor", &["lepidur", "lipeta", "lipettia", "lipidr", "lipita", "lipiter", "lippertia", "lobiter"]),
        ("Lovenox", &["levinox", "libemocks", "lovemax", "lovnix", "luvinox"]),
        ("lumpectomy", &["lumpicdomy", "lympectomy"]),
        ("lymphadenopathy", &["limfordenophy", "limphodenopathy", "lymphidenopathy", "lymphidinopathy", "lymphodenopathy", "lymphodenophy", "lymphodinophy", "lymphodonopithy", "lymphomopathy", "lymphoodonophy"]),
        ("melena", &["mailna", "mailner", "melaner", "mielena"]),
        ("methocarbamol", &["mafacabamo", "mathacobmol", "methacarbamill", "methacarbamol", "methacarbamyl", "methacarbemol", "metharbamol", "methicarbonyl"]),
        ("metoprolol", &["metaprobol", "metaproil", "metaproll", "mitaprol", "modapral"]),
        ("Miralax", &["meralax", "merlax", "moalax", "morelax", "muralax", "murelax", "murilox"]),
        ("Motrin", &["mephrin", "metrin", "moctram", "motran", "motron", "mutrin"]),
        ("mycophenolate", &["micafenilato", "mycofenylata", "mycophenylate", "mycophnolate", "mysophenolate"]),
        ("nebivolol", &["nebival", "nebivalal", "nebivol", "nebivolil", "nobival", "nobivol", "nubival"]),
        ("nystatin", &["nestaten", "nistadin", "nistatin", "nistatun", "nisterdon", "nistuten"]),
        ("oxybutynin", &["archibutanin", "axibutanin", "axibutinin", "exibutanin", "octabutanin", "oxabutanin", "oxabutanone", "oxybutanin"]),
        ("paracentesis", &["paracenses", "paracentasysh", "paracentes", "paracentios", "paracyntesis", "paracyntheses", "paracynthesis", "poracynthesis"]),
        ("patella", &["patelli", "paytala", "paytela", "paytella", "paytler", "putella", "pytela"]),
        ("Paxil", &["paxel", "paxol", "pecxel", "pockill", "poxel", "puxel", "puxil"]),
        ("petechiae", &["pdakey", "ptece", "ptekia", "pyteki"]),
        ("pharynx", &["farinx", "fharynx", "foreinx", "forinks", "furinks", "varynx"]),
        ("Plaquenil", &["plaquinil", "plaquinol", "plequinil", "pliquanil", "pliquinil", "ploquenil", "ploquinil", "pluquinil"]),
        ("pleura", &["pluru"]),
        ("Pravachol", &["pravachal", "pravakall", "pravakil", "pravattual", "pravetchel", "pravical", "pravichell", "pravicol", "pravishal", "pravishl", "privacle", "provacal", "provacol"]),
        ("prolactin", &["preluctin", "prolacin", "prolatin", "prolctin", "proletin", "proloctin", "prolocton", "proloctun", "prulluckedin"]),
        ("Proscar", &["prasca", "prascar", "prasir", "praskar", "presca", "priscar", "priscor", "proska"]),
        ("proteinuria", &["proteinori", "proteinuei", "protenuri", "protenuria", "protenurio", "protonura", "protonuria"]),
        ("pruritus", &["paritos", "poritus", "prioritis", "proitas", "proitash", "proritis", "proudis"]),
        ("psoriasis", &["sariasis", "soriaces", "soriasis", "soriasos", "soriasses"]),
        ("qid", &["wyyewski"]),
        ("rales", &["relez"]),
        ("Robaxin", &["rebacin", "rebaxin", "robackson", "robacson", "robuxen", "robuxin", "robuxon", "robuxun"]),
        ("Singulair", &["sangulair", "sengler", "singulare", "songulare", "sungulaire", "sungulare"]),
        ("spleen", &["splone", "spluin", "splun"]),
        ("splenomegaly", &["splanombly", "splenomboli", "splinombly"]),
        ("sulfasalazine", &["sulfasealazin", "sulfasealazine", "sulfazalazina", "sulfazalazini", "sulfisalicin"]),
        ("tadalafil", &["hodolafill", "tadalafal", "tadalafel", "tadaofel", "tadlathel", "tedolafol", "todolafel", "tootelafel"]),
        ("Tamiflu", &["hamul", "hemiflow", "tamaflu", "tamifil", "tamiflow", "tamifluff", "tanaflu", "tanifluve", "tanofil", "timaflu", "tumaflu"]),
        ("temazepam", &["hemazim", "hemisbaum", "temasbum", "temaspim", "temasum", "temazm"]),
        ("tendinitis", &["tandinitis", "tendernitis", "tendinitas", "tendonitos", "tondonitis", "tundinitis"]),
        ("testis", &["tistis"]),
        ("urinalysis", &["erinalysis"]),
        ("venous", &["fenush", "venosh", "venush", "weenos"]),
        ("Vyvanse", &["fivans", "vivanso", "vivansu", "vivensay"]),
        ("wheezing", &["wheezym", "wizung"]),
        ("Zocor", &["zaucier", "zekka", "zocca"]),
    ] },
    VocabPack { id: "legal", name: "Legal", description: "Law, contracts and legal procedure.", terms: &[
        ("accord", &["archord", "eccord"]),
        ("appellate", &["epilati", "epilatu", "ipolate", "ippolate", "uplate"]),
        ("appellee", &["apelli", "apellier", "epilee", "ippoli"]),
        ("assignee", &["ausinee"]),
        ("assignor", &["asanir", "essener", "isina", "isinuer", "issenia"]),
        ("causation", &["calcation", "calsatian", "causadion", "caussation", "corsation", "cossation", "cusation"]),
        ("codicil", &["citicel", "citicil", "citicill", "codacil", "codecol", "codecul", "codisle"]),
        ("counsel", &["seensel", "suncel", "suncil"]),
        ("debtor", &["dabdger", "dapta", "detof", "dibger", "dubger"]),
        ("devise", &["davisi", "deviceay", "diviso", "duvice"]),
        ("disbarment", &["dasparment", "disparmint", "disparmunt", "dusboment", "dusformant"]),
        ("dissolution", &["desaludion"]),
        ("FERPA", &["forpa", "fulpa", "furpo", "furpoo"]),
        ("foreperson", &["faperson", "furiperson", "furipusin", "vepsen"]),
        ("indemnitor", &["andonita", "indemisa", "indemita", "indemiter", "indemmitter", "indemnita", "indonissa", "indonita", "ondemitter", "undemeter"]),
        ("laches", &["lashish"]),
        ("leasehold", &["liesold", "louisold"]),
        ("lessee", &["lessu", "lussie"]),
        ("lessor", &["laucer"]),
        ("lienholder", &["lewinholder"]),
        ("mortgagee", &["morgagia", "mortgageu", "mortgagey", "mortgaju", "murgiji", "murgogy"]),
        ("NLRB", &["nlrbh"]),
        ("obligee", &["ablegy", "ibleci", "iblogy", "obligi", "obligia", "obligu", "obligy"]),
        ("offense", &["herfensi", "uffence"]),
        ("overruled", &["everold", "ivorald", "juvirold", "ovarulad", "overulad", "uvruld", "uvruled"]),
        ("plea", &["plivo"]),
        ("pretrial", &["petrial", "portrial", "pritrial", "protool", "protreol", "protrual", "putril", "putriol"]),
        ("rescission", &["rasition", "recisian", "recissian", "recissin", "resisian", "resisun"]),
        ("subpoena", &["sapbona", "saponu", "sipbona", "sipono", "sobburn", "sopuna", "subbona", "subbono", "subpono", "supena"]),
        ("tortfeasor", &["hertvser", "hortfisa", "torfisol", "tortfeaser", "turtfezer", "turtfisa", "turtviser"]),
        ("versus", &["versash", "versush"]),
        ("zoning", &["sonang", "sunang", "zonang"]),
    ] },
    VocabPack { id: "brands", name: "Brands", description: "Company, product and service names.", terms: &[
        ("adidas", &["addides", "additors", "addives", "adidos", "editus", "iditas", "odidas", "uditus"]),
        ("Adyen", &["adeyan", "adiane", "adyne", "adyun"]),
        ("Aetna", &["ayatna", "eatner", "eatney", "oatna", "oatner", "otena", "uitna"]),
        ("Affirm", &["offerm"]),
        ("Ameritrade", &["amaretraday", "amaritrade", "amartrady", "amarytread", "amarytro", "ameritrad", "ameritrada", "ameritradu", "amitrada", "emeritado", "emeritrade"]),
        ("Anker", &["anchir", "uncur"]),
        ("Anthropologie", &["anthropologio"]),
        ("Aperol", &["aberall", "aberel", "aperall", "eperol", "operol"]),
        ("Applebee's", &["applewis", "opelbees", "oppelbees", "applebees"]),
        ("Arby's", &["arbish", "herbis", "irvies", "arbys"]),
        ("ASUS", &["asush"]),
        ("Babybel", &["bobibul"]),
        ("Bai", &["bewey"]),
        ("Baileys", &["baelash", "bailice", "baylash"]),
        ("Bluesky", &["belusco", "bleiski", "bleisky", "bliwowski", "blowski", "bluarski", "bluuske", "bluyski", "buiski"]),
        ("Bose", &["bisaf"]),
        ("Breyers", &["braish", "brayesh"]),
        ("Campari", &["campair", "campara", "camparo", "campery", "gampara", "kampara", "kemparo", "sempuri", "simpari"]),
        ("Campbell's", &["campbellsch", "campbelsh", "compils", "cumpels", "campbells"]),
        ("CareerBuilder", &["careerbuildeer", "garabildor"]),
        ("CeraVe", &["carif", "serevey", "serive", "syrafu"]),
        ("Citroën", &["cetron", "citram", "citraun", "sitroon", "citroen"]),
        ("Conagra", &["canader", "canagra", "canagri", "canagro"]),
        ("Danaher", &["anaha", "danaha", "danar"]),
        ("Danone", &["dananu", "denona", "donon", "dunon"]),
        ("Depend", &["dapend", "dapon", "dipand", "dipond"]),
        ("Domino's", &["dawmines", "dominoche"]),
        ("Downy", &["delwi", "dolme"]),
        ("easyJet", &["easejot", "easyjat", "easyjit", "ezigath", "usijet"]),
        ("Enbridge", &["amberge", "enbridva", "inberge", "inbridge", "onbridge"]),
        ("ESPN", &["uspen"]),
        ("ETrade", &["itrada", "itrado", "itrata"]),
        ("Fage", &["fargi", "fargoo", "feach", "varte"]),
        ("Favor", &["favar"]),
        ("Folgers", &["falgers", "felges", "folgish", "volgish"]),
        ("French's", &["fronch", "frunchs", "frenchs"]),
        ("Gevalia", &["cuvalia", "gevlai", "govalia", "javalier", "javalio", "javeli", "javeliu", "javeliya", "jvaluo", "uvalia"]),
        ("Glossier", &["galesia", "glassair", "glesser", "glossair", "glossife", "glossila", "glossire", "glycider"]),
        ("GoToMeeting", &["getomitting", "gettermitting", "godometting", "gotometang", "gottermetting", "gottometting", "utomitting"]),
        ("IMDb", &["amdib", "armdb"]),
        ("InDesign", &["inderson", "indesun", "indusan", "indycen"]),
        ("Infosys", &["infases", "infasize", "infosis", "infosish", "infusies", "omfis", "unfosies"]),
        ("Instacart", &["anstacart", "instacarf", "instassert", "unstacart", "unstackart"]),
        ("InVision", &["anvision", "infison"]),
        ("Kahlúa", &["caluo", "colra", "kerlua", "kihua", "kolua", "koolua", "kulua", "kahlua"]),
        ("Kellogg", &["kellag", "kellig", "kilog", "kellogg"]),
        ("Kellogg's", &["calgs", "kalogs", "kelggs", "kelgs", "kellags", "kolgs", "kelloggs", "kellogs"]),
        ("Keurig", &["keyrig", "kurig"]),
        ("Kinder", &["kindar", "kindor"]),
        ("Kleenex", &["cleanux", "cleox", "clonex", "clonix", "cluinx", "kleenix", "kleinox"]),
        ("Kohl's", &["kitles", "kohls"]),
        ("Komatsu", &["cometsa", "kamatsu", "kimatsu", "komatza", "kumatsu"]),
        ("Kraft", &["crift"]),
        ("Letterboxd", &["latbux", "lutterboxed"]),
        ("Lidl", &["luddl"]),
        ("Linde", &["linno", "lynday"]),
        ("Lindt", &["linth"]),
        ("L'Oréal", &["lyrial", "lyrol", "lyural", "loreal", "l'oreal"]),
        ("Lowe's", &["loish", "lowiz", "lowes"]),
        ("Lysol", &["lyself"]),
        ("Macy's", &["masish", "massish", "macys"]),
        ("Marlboro", &["malbori", "marlbury", "merlborough", "mulbore"]),
        ("McCafé", &["macafo", "makafu", "mccaffre", "mccof", "mccugh", "mckefe", "mccafe"]),
        ("McDonald's", &["mcdennalls", "mcdonalds"]),
        ("Mentos", &["mentosh"]),
        ("Mercari", &["mercara", "mercaro", "morcary", "morcory", "morcurry"]),
        ("Michaels", &["mckills", "michelsh", "mikkles", "mocorolls", "moculs", "mokerals"]),
        ("Miralax", &["meralax", "merlax", "moalax", "morelax", "muralax", "murelax", "murilox"]),
        ("Moderna", &["miderna", "modeno", "modernu", "modnew", "modonu"]),
        ("Moncler", &["mainta", "mancla", "manklur", "mantler", "menkler", "monchr", "monclear", "monklar"]),
        ("Mondelēz", &["mandalus", "mendelas", "mendelis", "mindelis", "mondalaz", "mondolis", "mondulus", "mondelez", "mondela's"]),
        ("Moody's", &["maudis", "moities", "moudis", "moodys"]),
        ("Motrin", &["mephrin", "metrin", "moctram", "motran", "motron", "mutrin"]),
        ("Nathan's", &["nafons", "nathensh", "nothens", "nathans"]),
        ("Nestea", &["nesteo", "nestia", "nestie", "nestio", "nestir", "nustir", "nusty"]),
        ("NextEra", &["naxtra", "nextra", "nixtero", "nixtra", "noxra", "noxtra", "nuxtra"]),
        ("Nivea", &["naivu", "newvia", "niveye", "nyvory"]),
        ("Nucor", &["nokka", "nucer"]),
        ("OpenAI", &["apernye", "eperknife", "epini", "openo", "openr"]),
        ("Pantene", &["pantanay", "pantanu", "panteen", "pantenew", "panteney", "pantino", "pantonet", "pintin"]),
        ("Patrón", &["pecron", "pewtron", "pitrom", "pitron", "potron"]),
        ("Paychex", &["paychox", "paytrix", "poichux", "poitch"]),
        ("Powerade", &["pewaraid", "pivraid", "powerad", "powerado"]),
        ("Purell", &["purel", "puril"]),
        ("Rayovac", &["railvik", "raverk", "rayavac", "rayavok", "rayovic", "rayvoc", "reavac"]),
        ("Reckitt", &["recat", "recith"]),
        ("Reese's", &["reisos", "revese", "reeses"]),
        ("Regeneron", &["ragenern", "regeneran", "regenerin", "regenerine", "regenerun", "rijnern", "rojnaren", "rojnarn", "rojnarun"]),
        ("Revlon", &["revelan", "rivlan", "rivlen", "rivlon", "rovlin", "rovlon", "ruvlon"]),
        ("Robinhood", &["rabinha"]),
        ("Roche", &["rachu", "rochai"]),
        ("Shipt", &["shapt", "shept"]),
        ("Skechers", &["scachers", "sketchhars", "sketchish"]),
        ("Smirnoff", &["smern", "smurnoff", "smurnov", "smurnuff", "smyrn", "smyrniff", "smyrnoff"]),
        ("Softsoap", &["safsip", "saftuk", "softsoaf", "softsype", "softu", "suftop"]),
        ("Stryker", &["stricar"]),
        ("Swarovski", &["rorovsky", "swarosku", "swarovsk", "swarovska", "swarovsko", "swarska", "swarz", "swirovsky"]),
        ("Tidal", &["tetal", "todol", "tudle"]),
        ("Tito's", &["tartos", "titos"]),
        ("Tripadvisor", &["trepadvisor", "tripeadvisor", "tripervisal", "tripervisor", "tropadvisor", "tropivisor"]),
        ("Twizzlers", &["tooslers", "twazers", "tweslas", "twislers", "twistlers", "twizzliers", "twizzlish"]),
        ("Ubiquiti", &["abakiti", "abikidi", "ayukiti", "ubiquita", "ubkidu", "yubikido", "yubikita", "yubikiti"]),
        ("Velveeta", &["velbitu", "velvete", "velvita", "velvito", "vilbita", "vilvita", "volvedo"]),
        ("WeChat", &["watchat", "wetchat", "wetchut", "witchat"]),
        ("Wendy's", &["wondis", "wendys"]),
        ("Zeplin", &["sipplin", "suprin", "ziplin", "zipplin", "zuplin"]),
    ] },
    VocabPack { id: "names", name: "Names", description: "Common personal names.", terms: &[
        ("Acosta", &["acosto", "acusti", "ecosta", "euclusta", "icosta"]),
        ("Adeline", &["edline", "odline"]),
        ("Aguirre", &["aguary", "agwara", "agwaray", "agwery", "aquari", "uguara", "ugwar"]),
        ("Barnett", &["barnath", "barnot", "bornet"]),
        ("Bates", &["bitest"]),
        ("Becker", &["beccar", "bekia"]),
        ("Bose", &["bisaf"]),
        ("Brielle", &["brielli", "briello"]),
        ("Cabrera", &["cabro", "sebora", "sibra"]),
        ("Caldwell", &["sildwell"]),
        ("Camila", &["cumilla", "samilla", "semila"]),
        ("Carrillo", &["carilo", "corillo"]),
        ("Clarke", &["clarka", "clarker", "clarku"]),
        ("Conner", &["kaneer"]),
        ("Contreras", &["cantras", "centrus", "contreros", "kendraris", "sindrus"]),
        ("Debra", &["dubra"]),
        ("Dominguez", &["aemings", "domingoos", "domingoose", "domingous", "dominguis"]),
        ("Eleanor", &["alener", "olenr", "salinal"]),
        ("Elena", &["eilner"]),
        ("Elliott", &["oliot"]),
        ("Emmanuel", &["amanule", "aminule"]),
        ("Emmett", &["emmeth"]),
        ("Farooq", &["faroak", "farroc", "farrok", "firuk"]),
        ("Figueroa", &["fagaroa", "fagroa", "fegaroa", "fewgaro", "figaroi", "figaroo", "figaroy", "figoroa", "figrower", "figuro", "fugaroa"]),
        ("Fischer", &["fiska", "fiskar", "fushur"]),
        ("Frances", &["francesch", "francus", "frankus", "frencis", "frensis"]),
        ("Gabriela", &["gabrielou", "gabrilli", "galperilla"]),
        ("Gardner", &["gardenar", "gerdner"]),
        ("Garner", &["garnia"]),
        ("Garza", &["garzu", "gerza", "gurza", "jurza", "scarzu"]),
        ("Gray", &["grifa"]),
        ("Greene", &["greena"]),
        ("Hanson", &["hansun", "hintson", "hunson"]),
        ("Hines", &["heinesch", "henus"]),
        ("Holmes", &["hillmiz", "hilmus", "homus"]),
        ("Howell", &["hiwol"]),
        ("Hussain", &["hasane", "husseyon"]),
        ("Inoue", &["inawi", "inwar"]),
        ("Isaac", &["esark", "essach", "iseec", "iseok", "usarc", "uzuck"]),
        ("Juarez", &["jewersh", "jewesh", "juaros"]),
        ("Kane", &["kanyu"]),
        ("Katherine", &["cafarina", "cafarinu", "cafferino", "catharinu", "catherinew", "cutherine", "kaffarin"]),
        ("Kathryn", &["citherin", "kitherin"]),
        ("Kato", &["cartu"]),
        ("Kelley", &["kelloy", "kelwi"]),
        ("Khloe", &["khlife", "khloo"]),
        ("Leach", &["luach", "lyach"]),
        ("Leilani", &["leylane", "leylang", "liulani"]),
        ("Leticia", &["larticia", "letasi", "letisuo"]),
        ("Lindsey", &["lindsyfe", "linsoy"]),
        ("McGuire", &["maguaru", "maguiro", "magware", "majaya", "mcguery", "mcgure", "megwar"]),
        ("Mehta", &["meitu"]),
        ("Moreno", &["morno", "mornu", "myrno"]),
        ("Moyer", &["mayair"]),
        ("Mukherjee", &["macag", "macajo", "makajeo", "makerji", "markagier", "matcajia", "mechurgy", "mikergy", "muckage", "muckerjoo", "muckherge", "mukherchie"]),
        ("Naidu", &["naiju", "neidu", "noidu", "noilu"]),
        ("Nevaeh", &["novare", "novay"]),
        ("Ngo", &["unjai"]),
        ("Nichols", &["nishosh"]),
        ("Peters", &["petish"]),
        ("Peyton", &["penotin"]),
        ("Phillips", &["phalettes", "philipsh"]),
        ("Qureshi", &["goreshi", "koreshi", "kyirchi", "quaresh", "quareshi", "quaresho", "quareshu"]),
        ("Rahman", &["rihman"]),
        ("Reid", &["roude"]),
        ("Rivas", &["reavas", "reavos"]),
        ("Robbins", &["robinch"]),
        ("Rodgers", &["reggers", "rogish"]),
        ("Ruben", &["reben"]),
        ("Ryker", &["raikir", "rikar", "rikear"]),
        ("Saini", &["sahini", "seinu", "sieni", "suini"]),
        ("Scarlett", &["scarlop", "scarlot"]),
        ("Schmitt", &["schmat", "schmet", "schmott"]),
        ("Shah", &["shuffer"]),
        ("Shaikh", &["schoyk", "schroik"]),
        ("Silva", &["silvu"]),
        ("Silvia", &["solvia", "sylvei", "sylvu"]),
        ("Sofia", &["sofire", "sofoo"]),
        ("Stephens", &["steffench", "stefinch", "stoffens", "stuffens"]),
        ("Stewart", &["staward"]),
        ("Suarez", &["sarez", "sewaras", "seweros", "suaris"]),
        ("Theresa", &["thessie", "thesso", "thurasa"]),
        ("Torres", &["torresh", "torush"]),
        ("Vazquez", &["falskwis", "faskus", "fasquesh", "foskis", "fuzgus", "vasquewas", "vasquis", "vazkis", "vosgus", "voskis"]),
        ("Velazquez", &["philasis", "philassis", "velasgrish", "velasis", "velasquiz", "vellusquish"]),
        ("Waylon", &["wailn"]),
        ("Webb", &["swarb"]),
        ("Williamson", &["wallapson", "woliamson"]),
        ("Wolfe", &["wolfu"]),
        ("Yadav", &["yadder", "yolda"]),
    ] },
];

/// Finds a pack by id.
pub fn find(id: &str) -> Option<&'static VocabPack> {
    PACKS.iter().find(|p| p.id == id)
}

/// All built-in packs, in display order.
pub fn all() -> &'static [VocabPack] {
    PACKS
}

/// One flattened pack term for the correction tier (lowercased).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackTerm {
    /// Canonical spelling (lowercased for matching; the original casing is
    /// not preserved — pack terms are common nouns/brand spellings).
    pub canonical: String,
    /// A known mis-hearing alias (lowercased).
    pub alias: String,
}

/// Flattens the enabled packs into (canonical, alias) pairs for the
/// correction tier. Precompute once per dictation, not per token.
pub fn terms_for(enabled_ids: &[String]) -> Vec<PackTerm> {
    let mut out = Vec::new();
    for p in PACKS.iter().filter(|p| enabled_ids.iter().any(|id| *id == p.id)) {
        for (canonical, aliases) in p.terms {
            let c = canonical.to_lowercase();
            for a in *aliases {
                let alias = a.to_lowercase();
                out.push(PackTerm {
                    canonical: c.clone(),
                    alias,
                });
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn find_returns_each_pack_and_none_for_unknown() {
        assert_eq!(find("tech").map(|p| p.name), Some("Technology"));
        assert_eq!(find("medical").map(|p| p.name), Some("Medical"));
        assert_eq!(find("legal").map(|p| p.name), Some("Legal"));
        assert_eq!(find("brands").map(|p| p.name), Some("Brands"));
        assert_eq!(find("names").map(|p| p.name), Some("Names"));
        assert!(find("nope").is_none());
        assert_eq!(all().len(), 5);
    }

    #[test]
    fn terms_for_flattens_only_enabled_packs_lowercased() {
        let terms = terms_for(&["tech".to_string()]);
        assert!(!terms.is_empty());
        assert!(terms.iter().all(|t| t.canonical == t.canonical.to_lowercase()));
        assert!(terms.iter().all(|t| t.alias == t.alias.to_lowercase()));
        // "cherrypick" -> "cherapak" must be present (reference data).
        assert!(terms.iter().any(|t| t.canonical == "cherrypick" && t.alias == "cherapak"));
        // Disabling everything yields no terms.
        assert!(terms_for(&[]).is_empty());
        // Unknown ids are ignored.
        assert!(terms_for(&["nope".to_string()]).is_empty());
        // Two packs combine.
        let two = terms_for(&["tech".to_string(), "legal".to_string()]);
        assert!(two.len() > terms.len() || two.len() > terms_for(&["legal".to_string()]).len());
    }
}
